Page:
  extensions:
   - WidgetPageExtension
   - BlogCategoryExtension
SiteConfig:
  extensions:
    - SiteConfigExtension
TypeKit:
  typekitID: gor3pds
URLSegmentFilter:
  default_allow_multibyte: true